name: 🚀 Deploy to Namecheap via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Upload build to Namecheap Hosting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies and build
      - name: Install and build project
        run: |
          npm ci
          npm run build

      # Step 4: Debug - list dist folder contents
      - name: Debug: List contents of dist/
        run: ls -la dist

      # Step 5: Deploy via FTP
      - name: Deploy to Namecheap FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /
